// Vercel wrapper for the emiten chatbot.
//
// Nine lines on purpose. All the logic lives in api/_chat-impl.ts, which
// `npm run build` bundles into api/_chat-bundle.mjs — a single self-contained
// ESM module with no relative imports left to resolve. See the header of
// _chat-impl.ts for why: the first version imported src/ directly and Vercel
// failed to load the module at all, on every request including GET.

import type { VercelRequest, VercelResponse } from '@vercel/node';
// ts-ignore rather than ts-expect-error: the bundle is generated by
// `npm run build:chatfn`, so whether TypeScript can resolve it depends on
// whether that step has run yet. `expect-error` would itself become an error on
// the runs where it CAN resolve it.
// @ts-ignore
import { handleChat } from './_chat-bundle.mjs';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Gunakan POST.' });
    return;
  }
  const { status, body } = await handleChat(req, (req.body ?? {}) as Record<string, unknown>);
  res.setHeader('Cache-Control', 'no-store');
  res.status(status).json(body);
}
